/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1PortStatus struct {
	Error_ string `json:"error,omitempty"`
	Port int32 `json:"port,omitempty"`
	Protocol string `json:"protocol,omitempty"`
}
