/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryRefs struct {
	Branches []string `json:"branches,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
