/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// RepositoryList is a collection of Repositories.
type V1alpha1RepoCredsList struct {
	Items []V1alpha1RepoCreds `json:"items,omitempty"`
	Metadata *V1ListMeta `json:"metadata,omitempty"`
}
