/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterHelp struct {
	ChatText string `json:"chatText,omitempty"`
	ChatUrl string `json:"chatUrl,omitempty"`
}
