/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationSourceJsonnet struct {
	ExtVars []V1alpha1JsonnetVar `json:"extVars,omitempty"`
	Libs []string `json:"libs,omitempty"`
	Tlas []V1alpha1JsonnetVar `json:"tlas,omitempty"`
}
