/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1OrphanedResourcesMonitorSettings struct {
	Ignore []V1alpha1OrphanedResourceKey `json:"ignore,omitempty"`
	Warn bool `json:"warn,omitempty"`
}
