/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1HostInfo struct {
	Name string `json:"name,omitempty"`
	ResourcesInfo []V1alpha1HostResourceInfo `json:"resourcesInfo,omitempty"`
	SystemInfo *V1NodeSystemInfo `json:"systemInfo,omitempty"`
}
