/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryKsonnetEnvironmentDestination struct {
	Namespace string `json:"namespace,omitempty"`
	// Server is the Kubernetes server that the cluster is running on.
	Server string `json:"server,omitempty"`
}
