/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ApplicationWatchEvent contains information about application change.
type V1alpha1ApplicationWatchEvent struct {
	Application *V1alpha1Application `json:"application,omitempty"`
	Type_ string `json:"type,omitempty"`
}
