/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectSyncWindowsResponse struct {
	Windows []V1alpha1SyncWindow `json:"windows,omitempty"`
}
