/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationApplicationSyncRequest struct {
	DryRun bool `json:"dryRun,omitempty"`
	Infos []V1alpha1Info `json:"infos,omitempty"`
	Manifests []string `json:"manifests,omitempty"`
	Name string `json:"name,omitempty"`
	Prune bool `json:"prune,omitempty"`
	Resources []V1alpha1SyncOperationResource `json:"resources,omitempty"`
	RetryStrategy *V1alpha1RetryStrategy `json:"retryStrategy,omitempty"`
	Revision string `json:"revision,omitempty"`
	Strategy *V1alpha1SyncStrategy `json:"strategy,omitempty"`
	SyncOptions *ApplicationSyncOptions `json:"syncOptions,omitempty"`
}
