/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// LoadBalancerIngress represents the status of a load-balancer ingress point: traffic intended for the service should be sent to an ingress point.
type V1LoadBalancerIngress struct {
	Hostname string `json:"hostname,omitempty"`
	Ip string `json:"ip,omitempty"`
	Ports []V1PortStatus `json:"ports,omitempty"`
}
