/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationSourceKustomize struct {
	CommonAnnotations map[string]string `json:"commonAnnotations,omitempty"`
	CommonLabels map[string]string `json:"commonLabels,omitempty"`
	ForceCommonAnnotations bool `json:"forceCommonAnnotations,omitempty"`
	ForceCommonLabels bool `json:"forceCommonLabels,omitempty"`
	Images []string `json:"images,omitempty"`
	NamePrefix string `json:"namePrefix,omitempty"`
	NameSuffix string `json:"nameSuffix,omitempty"`
	Version string `json:"version,omitempty"`
}
