/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterSettings struct {
	AppLabelKey string `json:"appLabelKey,omitempty"`
	ConfigManagementPlugins []V1alpha1ConfigManagementPlugin `json:"configManagementPlugins,omitempty"`
	DexConfig *ClusterDexConfig `json:"dexConfig,omitempty"`
	GoogleAnalytics *ClusterGoogleAnalyticsConfig `json:"googleAnalytics,omitempty"`
	Help *ClusterHelp `json:"help,omitempty"`
	KustomizeOptions *V1alpha1KustomizeOptions `json:"kustomizeOptions,omitempty"`
	KustomizeVersions []string `json:"kustomizeVersions,omitempty"`
	OidcConfig *ClusterOidcConfig `json:"oidcConfig,omitempty"`
	PasswordPattern string `json:"passwordPattern,omitempty"`
	Plugins []ClusterPlugin `json:"plugins,omitempty"`
	ResourceOverrides map[string]V1alpha1ResourceOverride `json:"resourceOverrides,omitempty"`
	StatusBadgeEnabled bool `json:"statusBadgeEnabled,omitempty"`
	TrackingMethod string `json:"trackingMethod,omitempty"`
	UiBannerContent string `json:"uiBannerContent,omitempty"`
	UiBannerPermanent bool `json:"uiBannerPermanent,omitempty"`
	UiBannerPosition string `json:"uiBannerPosition,omitempty"`
	UiBannerURL string `json:"uiBannerURL,omitempty"`
	UiCssURL string `json:"uiCssURL,omitempty"`
	Url string `json:"url,omitempty"`
	UserLoginsDisabled bool `json:"userLoginsDisabled,omitempty"`
}
