/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationApplicationPatchRequest struct {
	Name string `json:"name,omitempty"`
	Patch string `json:"patch,omitempty"`
	PatchType string `json:"patchType,omitempty"`
}
