/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Cluster struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	// Indicates if cluster level resources should be managed. This setting is used only if cluster is connected in a namespaced mode.
	ClusterResources bool `json:"clusterResources,omitempty"`
	Config *V1alpha1ClusterConfig `json:"config,omitempty"`
	ConnectionState *V1alpha1ConnectionState `json:"connectionState,omitempty"`
	Info *V1alpha1ClusterInfo `json:"info,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	Name string `json:"name,omitempty"`
	// Holds list of namespaces which are accessible in that cluster. Cluster level resources will be ignored if namespace list is not empty.
	Namespaces []string `json:"namespaces,omitempty"`
	Project string `json:"project,omitempty"`
	RefreshRequestedAt *V1Time `json:"refreshRequestedAt,omitempty"`
	Server string `json:"server,omitempty"`
	ServerVersion string `json:"serverVersion,omitempty"`
	// Shard contains optional shard number. Calculated on the fly by the application controller if not specified.
	Shard string `json:"shard,omitempty"`
}
