/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationStatus struct {
	Conditions []V1alpha1ApplicationCondition `json:"conditions,omitempty"`
	Health *V1alpha1HealthStatus `json:"health,omitempty"`
	History []V1alpha1RevisionHistory `json:"history,omitempty"`
	ObservedAt *V1Time `json:"observedAt,omitempty"`
	OperationState *V1alpha1OperationState `json:"operationState,omitempty"`
	ReconciledAt *V1Time `json:"reconciledAt,omitempty"`
	Resources []V1alpha1ResourceStatus `json:"resources,omitempty"`
	SourceType string `json:"sourceType,omitempty"`
	Summary *V1alpha1ApplicationSummary `json:"summary,omitempty"`
	Sync *V1alpha1SyncStatus `json:"sync,omitempty"`
}
