/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RuntimeStreamError struct {
	Details []ProtobufAny `json:"details,omitempty"`
	GrpcCode int32 `json:"grpc_code,omitempty"`
	HttpCode int32 `json:"http_code,omitempty"`
	HttpStatus string `json:"http_status,omitempty"`
	Message string `json:"message,omitempty"`
}
