/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1AppProjectSpec struct {
	ClusterResourceBlacklist []V1GroupKind `json:"clusterResourceBlacklist,omitempty"`
	ClusterResourceWhitelist []V1GroupKind `json:"clusterResourceWhitelist,omitempty"`
	Description string `json:"description,omitempty"`
	Destinations []V1alpha1ApplicationDestination `json:"destinations,omitempty"`
	NamespaceResourceBlacklist []V1GroupKind `json:"namespaceResourceBlacklist,omitempty"`
	NamespaceResourceWhitelist []V1GroupKind `json:"namespaceResourceWhitelist,omitempty"`
	OrphanedResources *V1alpha1OrphanedResourcesMonitorSettings `json:"orphanedResources,omitempty"`
	Roles []V1alpha1ProjectRole `json:"roles,omitempty"`
	SignatureKeys []V1alpha1SignatureKey `json:"signatureKeys,omitempty"`
	SourceRepos []string `json:"sourceRepos,omitempty"`
	SyncWindows []V1alpha1SyncWindow `json:"syncWindows,omitempty"`
}
