/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationApplicationSyncWindow struct {
	Duration string `json:"duration,omitempty"`
	Kind string `json:"kind,omitempty"`
	ManualSync bool `json:"manualSync,omitempty"`
	Schedule string `json:"schedule,omitempty"`
}
