/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// EventList is a list of events.
type V1EventList struct {
	Items []V1Event `json:"items,omitempty"`
	Metadata *V1ListMeta `json:"metadata,omitempty"`
}
