/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountAccount struct {
	Capabilities []string `json:"capabilities,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Name string `json:"name,omitempty"`
	Tokens []AccountToken `json:"tokens,omitempty"`
}
