/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1KsonnetParameter struct {
	Component string `json:"component,omitempty"`
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
