/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// SessionResponse wraps the created token or returns an empty string if deleted.
type SessionSessionResponse struct {
	Token string `json:"token,omitempty"`
}
