/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Application struct {
	Metadata *V1ObjectMeta `json:"metadata,omitempty"`
	Operation *V1alpha1Operation `json:"operation,omitempty"`
	Spec *V1alpha1ApplicationSpec `json:"spec,omitempty"`
	Status *V1alpha1ApplicationStatus `json:"status,omitempty"`
}
