/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationSourceDirectory struct {
	Exclude string `json:"exclude,omitempty"`
	Include string `json:"include,omitempty"`
	Jsonnet *V1alpha1ApplicationSourceJsonnet `json:"jsonnet,omitempty"`
	Recurse bool `json:"recurse,omitempty"`
}
