/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectProjectUpdateRequest struct {
	Project *V1alpha1AppProject `json:"project,omitempty"`
}
