/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryAppInfo struct {
	Path string `json:"path,omitempty"`
	Type_ string `json:"type,omitempty"`
}
