/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceOverride struct {
	Actions string `json:"actions,omitempty"`
	HealthLua string `json:"healthLua,omitempty"`
	IgnoreDifferences *V1alpha1OverrideIgnoreDiff `json:"ignoreDifferences,omitempty"`
	KnownTypeFields []V1alpha1KnownTypeField `json:"knownTypeFields,omitempty"`
	UseOpenLibs bool `json:"useOpenLibs,omitempty"`
}
