/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1OverrideIgnoreDiff struct {
	JSONPointers []string `json:"jSONPointers,omitempty"`
	JqPathExpressions []string `json:"jqPathExpressions,omitempty"`
}
