/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryHelmAppSpec struct {
	FileParameters []V1alpha1HelmFileParameter `json:"fileParameters,omitempty"`
	Name string `json:"name,omitempty"`
	Parameters []V1alpha1HelmParameter `json:"parameters,omitempty"`
	ValueFiles []string `json:"valueFiles,omitempty"`
	Values string `json:"values,omitempty"`
}
