/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ProjectTokenCreateRequest defines project token creation parameters.
type ProjectProjectTokenCreateRequest struct {
	Description string `json:"description,omitempty"`
	ExpiresIn string `json:"expiresIn,omitempty"`
	Id string `json:"id,omitempty"`
	Project string `json:"project,omitempty"`
	Role string `json:"role,omitempty"`
}
