/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
type V1NodeSystemInfo struct {
	Architecture string `json:"architecture,omitempty"`
	// Boot ID reported by the node.
	BootID string `json:"bootID,omitempty"`
	// ContainerRuntime Version reported by the node through runtime remote API (e.g. docker://1.5.0).
	ContainerRuntimeVersion string `json:"containerRuntimeVersion,omitempty"`
	// Kernel Version reported by the node from 'uname -r' (e.g. 3.16.0-0.bpo.4-amd64).
	KernelVersion string `json:"kernelVersion,omitempty"`
	// KubeProxy Version reported by the node.
	KubeProxyVersion string `json:"kubeProxyVersion,omitempty"`
	// Kubelet Version reported by the node.
	KubeletVersion string `json:"kubeletVersion,omitempty"`
	MachineID string `json:"machineID,omitempty"`
	OperatingSystem string `json:"operatingSystem,omitempty"`
	// OS Image reported by the node from /etc/os-release (e.g. Debian GNU/Linux 7 (wheezy)).
	OsImage string `json:"osImage,omitempty"`
	SystemUUID string `json:"systemUUID,omitempty"`
}
