/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountUpdatePasswordRequest struct {
	CurrentPassword string `json:"currentPassword,omitempty"`
	Name string `json:"name,omitempty"`
	NewPassword string `json:"newPassword,omitempty"`
}
