/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClusterGoogleAnalyticsConfig struct {
	AnonymizeUsers bool `json:"anonymizeUsers,omitempty"`
	TrackingID string `json:"trackingID,omitempty"`
}
