/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1JwtToken struct {
	Exp string `json:"exp,omitempty"`
	Iat string `json:"iat,omitempty"`
	Id string `json:"id,omitempty"`
}
