/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Backoff struct {
	Duration string `json:"duration,omitempty"`
	Factor string `json:"factor,omitempty"`
	MaxDuration string `json:"maxDuration,omitempty"`
}
