/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// SyncOperation contains details about a sync operation.
type V1alpha1SyncOperation struct {
	DryRun bool `json:"dryRun,omitempty"`
	Manifests []string `json:"manifests,omitempty"`
	Prune bool `json:"prune,omitempty"`
	Resources []V1alpha1SyncOperationResource `json:"resources,omitempty"`
	// Revision is the revision (Git) or chart version (Helm) which to sync the application to If omitted, will use the revision specified in app spec.
	Revision string `json:"revision,omitempty"`
	Source *V1alpha1ApplicationSource `json:"source,omitempty"`
	SyncOptions []string `json:"syncOptions,omitempty"`
	SyncStrategy *V1alpha1SyncStrategy `json:"syncStrategy,omitempty"`
}
