/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// EventSource contains information for an event.
type V1EventSource struct {
	Component string `json:"component,omitempty"`
	Host string `json:"host,omitempty"`
}
