/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GpgkeyGnuPgPublicKeyCreateResponse struct {
	Created *V1alpha1GnuPgPublicKeyList `json:"created,omitempty"`
	Skipped []string `json:"skipped,omitempty"`
}
