/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryManifestResponse struct {
	Manifests []string `json:"manifests,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Revision string `json:"revision,omitempty"`
	Server string `json:"server,omitempty"`
	SourceType string `json:"sourceType,omitempty"`
	VerifyResult string `json:"verifyResult,omitempty"`
}
