/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ResourceIgnoreDifferences contains resource filter and list of json paths which should be ignored during comparison with live state.
type V1alpha1ResourceIgnoreDifferences struct {
	Group string `json:"group,omitempty"`
	JqPathExpressions []string `json:"jqPathExpressions,omitempty"`
	JsonPointers []string `json:"jsonPointers,omitempty"`
	Kind string `json:"kind,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
}
