/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationSourceHelm struct {
	FileParameters []V1alpha1HelmFileParameter `json:"fileParameters,omitempty"`
	Parameters []V1alpha1HelmParameter `json:"parameters,omitempty"`
	PassCredentials bool `json:"passCredentials,omitempty"`
	ReleaseName string `json:"releaseName,omitempty"`
	ValueFiles []string `json:"valueFiles,omitempty"`
	Values string `json:"values,omitempty"`
	Version string `json:"version,omitempty"`
}
