/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectDetailedProjectsResponse struct {
	Clusters []V1alpha1Cluster `json:"clusters,omitempty"`
	GlobalProjects []V1alpha1AppProject `json:"globalProjects,omitempty"`
	Project *V1alpha1AppProject `json:"project,omitempty"`
	Repositories []V1alpha1Repository `json:"repositories,omitempty"`
}
