/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RepositoryCertificate struct {
	CertData string `json:"certData,omitempty"`
	CertInfo string `json:"certInfo,omitempty"`
	CertSubType string `json:"certSubType,omitempty"`
	CertType string `json:"certType,omitempty"`
	ServerName string `json:"serverName,omitempty"`
}
