/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1OwnerReference struct {
	// API version of the referent.
	ApiVersion string `json:"apiVersion,omitempty"`
	BlockOwnerDeletion bool `json:"blockOwnerDeletion,omitempty"`
	Controller bool `json:"controller,omitempty"`
	Kind string `json:"kind,omitempty"`
	Name string `json:"name,omitempty"`
	Uid string `json:"uid,omitempty"`
}
