/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1Operation struct {
	Info []V1alpha1Info `json:"info,omitempty"`
	InitiatedBy *V1alpha1OperationInitiator `json:"initiatedBy,omitempty"`
	Retry *V1alpha1RetryStrategy `json:"retry,omitempty"`
	Sync *V1alpha1SyncOperation `json:"sync,omitempty"`
}
