/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RuntimeError struct {
	Code int32 `json:"code,omitempty"`
	Details []ProtobufAny `json:"details,omitempty"`
	Error_ string `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
}
