/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryKsonnetEnvironment struct {
	Destination *RepositoryKsonnetEnvironmentDestination `json:"destination,omitempty"`
	// KubernetesVersion is the kubernetes version the targeted cluster is running on.
	K8sVersion string `json:"k8sVersion,omitempty"`
	Name string `json:"name,omitempty"`
}
