/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationApplicationSyncWindowsResponse struct {
	ActiveWindows []ApplicationApplicationSyncWindow `json:"activeWindows,omitempty"`
	AssignedWindows []ApplicationApplicationSyncWindow `json:"assignedWindows,omitempty"`
	CanSync bool `json:"canSync,omitempty"`
}
