/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceDiff struct {
	Diff string `json:"diff,omitempty"`
	Group string `json:"group,omitempty"`
	Hook bool `json:"hook,omitempty"`
	Kind string `json:"kind,omitempty"`
	LiveState string `json:"liveState,omitempty"`
	Modified bool `json:"modified,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	NormalizedLiveState string `json:"normalizedLiveState,omitempty"`
	PredictedLiveState string `json:"predictedLiveState,omitempty"`
	ResourceVersion string `json:"resourceVersion,omitempty"`
	TargetState string `json:"targetState,omitempty"`
}
