/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApplicationApplicationRollbackRequest struct {
	DryRun bool `json:"dryRun,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Prune bool `json:"prune,omitempty"`
}
