/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationTree struct {
	Hosts []V1alpha1HostInfo `json:"hosts,omitempty"`
	// Nodes contains list of nodes which either directly managed by the application and children of directly managed nodes.
	Nodes []V1alpha1ResourceNode `json:"nodes,omitempty"`
	// OrphanedNodes contains if or orphaned nodes: nodes which are not managed by the app but in the same namespace. List is populated only if orphaned resources enabled in app project.
	OrphanedNodes []V1alpha1ResourceNode `json:"orphanedNodes,omitempty"`
}
