/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1SyncWindow struct {
	Applications []string `json:"applications,omitempty"`
	Clusters []string `json:"clusters,omitempty"`
	Duration string `json:"duration,omitempty"`
	Kind string `json:"kind,omitempty"`
	ManualSync bool `json:"manualSync,omitempty"`
	Namespaces []string `json:"namespaces,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	TimeZone string `json:"timeZone,omitempty"`
}
