/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationSourceKsonnet struct {
	Environment string `json:"environment,omitempty"`
	Parameters []V1alpha1KsonnetParameter `json:"parameters,omitempty"`
}
