/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AccountCreateTokenRequest struct {
	ExpiresIn string `json:"expiresIn,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
