/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ApplicationDestination struct {
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Server string `json:"server,omitempty"`
}
