/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// SyncStrategyHook will perform a sync using hooks annotations. If no hook annotation is specified falls back to `kubectl apply`.
type V1alpha1SyncStrategyHook struct {
	SyncStrategyApply *V1alpha1SyncStrategyApply `json:"syncStrategyApply,omitempty"`
}
