/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VersionVersionMessage struct {
	BuildDate string `json:"BuildDate,omitempty"`
	Compiler string `json:"Compiler,omitempty"`
	GitCommit string `json:"GitCommit,omitempty"`
	GitTag string `json:"GitTag,omitempty"`
	GitTreeState string `json:"GitTreeState,omitempty"`
	GoVersion string `json:"GoVersion,omitempty"`
	HelmVersion string `json:"HelmVersion,omitempty"`
	JsonnetVersion string `json:"JsonnetVersion,omitempty"`
	KsonnetVersion string `json:"KsonnetVersion,omitempty"`
	KubectlVersion string `json:"KubectlVersion,omitempty"`
	KustomizeVersion string `json:"KustomizeVersion,omitempty"`
	Platform string `json:"Platform,omitempty"`
	Version string `json:"Version,omitempty"`
}
