/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ClusterList is a collection of Clusters.
type V1alpha1ClusterList struct {
	Items []V1alpha1Cluster `json:"items,omitempty"`
	Metadata *V1ListMeta `json:"metadata,omitempty"`
}
