/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1GnuPgPublicKeyList struct {
	Items []V1alpha1GnuPgPublicKey `json:"items,omitempty"`
	Metadata *V1ListMeta `json:"metadata,omitempty"`
}
