/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1HostResourceInfo struct {
	Capacity string `json:"capacity,omitempty"`
	RequestedByApp string `json:"requestedByApp,omitempty"`
	RequestedByNeighbors string `json:"requestedByNeighbors,omitempty"`
	ResourceName string `json:"resourceName,omitempty"`
}
