/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceAction struct {
	Disabled bool `json:"disabled,omitempty"`
	Name string `json:"name,omitempty"`
	Params []V1alpha1ResourceActionParam `json:"params,omitempty"`
}
