/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1SyncStatus struct {
	ComparedTo *V1alpha1ComparedTo `json:"comparedTo,omitempty"`
	Revision string `json:"revision,omitempty"`
	Status string `json:"status,omitempty"`
}
