/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryRepoAppDetailsQuery struct {
	AppName string `json:"appName,omitempty"`
	Source *V1alpha1ApplicationSource `json:"source,omitempty"`
}
