/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RepositoryKsonnetAppSpec struct {
	Environments map[string]RepositoryKsonnetEnvironment `json:"environments,omitempty"`
	Name string `json:"name,omitempty"`
	Parameters []V1alpha1KsonnetParameter `json:"parameters,omitempty"`
}
