/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1SyncPolicyAutomated struct {
	AllowEmpty bool `json:"allowEmpty,omitempty"`
	Prune bool `json:"prune,omitempty"`
	SelfHeal bool `json:"selfHeal,omitempty"`
}
