/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1RevisionMetadata struct {
	Author string `json:"author,omitempty"`
	Date *V1Time `json:"date,omitempty"`
	Message string `json:"message,omitempty"`
	// SignatureInfo contains a hint on the signer if the revision was signed with GPG, and signature verification is enabled.
	SignatureInfo string `json:"signatureInfo,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
