/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ClusterCacheInfo struct {
	ApisCount string `json:"apisCount,omitempty"`
	LastCacheSyncTime *V1Time `json:"lastCacheSyncTime,omitempty"`
	ResourcesCount string `json:"resourcesCount,omitempty"`
}
