/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceStatus struct {
	Group string `json:"group,omitempty"`
	Health *V1alpha1HealthStatus `json:"health,omitempty"`
	Hook bool `json:"hook,omitempty"`
	Kind string `json:"kind,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	RequiresPruning bool `json:"requiresPruning,omitempty"`
	Status string `json:"status,omitempty"`
	Version string `json:"version,omitempty"`
}
