/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceNode struct {
	CreatedAt *V1Time `json:"createdAt,omitempty"`
	Health *V1alpha1HealthStatus `json:"health,omitempty"`
	Images []string `json:"images,omitempty"`
	Info []V1alpha1InfoItem `json:"info,omitempty"`
	NetworkingInfo *V1alpha1ResourceNetworkingInfo `json:"networkingInfo,omitempty"`
	ParentRefs []V1alpha1ResourceRef `json:"parentRefs,omitempty"`
	ResourceRef *V1alpha1ResourceRef `json:"resourceRef,omitempty"`
	ResourceVersion string `json:"resourceVersion,omitempty"`
}
