/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ComparedTo struct {
	Destination *V1alpha1ApplicationDestination `json:"destination,omitempty"`
	Source *V1alpha1ApplicationSource `json:"source,omitempty"`
}
