/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1SyncStrategy struct {
	Apply *V1alpha1SyncStrategyApply `json:"apply,omitempty"`
	Hook *V1alpha1SyncStrategyHook `json:"hook,omitempty"`
}
