/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// +protobuf.options.(gogoproto.goproto_stringer)=false
type V1GroupKind struct {
	Group string `json:"group,omitempty"`
	Kind string `json:"kind,omitempty"`
}
