/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
type V1EventSeries struct {
	Count int32 `json:"count,omitempty"`
	LastObservedTime *V1MicroTime `json:"lastObservedTime,omitempty"`
}
