/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1KnownTypeField struct {
	Field string `json:"field,omitempty"`
	Type_ string `json:"type,omitempty"`
}
