/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1ResourceNetworkingInfo struct {
	// ExternalURLs holds list of URLs which should be available externally. List is populated for ingress resources using rules hostnames.
	ExternalURLs []string `json:"externalURLs,omitempty"`
	Ingress []V1LoadBalancerIngress `json:"ingress,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	TargetLabels map[string]string `json:"targetLabels,omitempty"`
	TargetRefs []V1alpha1ResourceRef `json:"targetRefs,omitempty"`
}
