/*
 * Consolidate Services
 *
 * Description of all APIs
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1alpha1AppProjectStatus struct {
	JwtTokensByRole map[string]V1alpha1JwtTokens `json:"jwtTokensByRole,omitempty"`
}
